#!/bin/sh
#


clean:
	#rm -f ctypes_openssl_generated.c ctypes_openssl_generated_clean.c ctypes_openssl_generated.py ctypes_openssl_generated.pyc
	rm -f ctypes_nss_generated.c ctypes_nss_generated_clean.c ctypes_nss_generated.py ctypes_nss_generated.pyc

